volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./
    env_file: .env
    volumes:
      - ./farpost/static:/backend_static
    depends_on:
      - db

  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - ./farpost/static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - backend
